flow-config:
  defaults: # Add your projects default settings here
  services:
    CodeFoundation\FlowConfig\Repository\ReadonlyConfig:
      arguments:
        $config: "%flow-config.defaults%"
    CodeFoundation\FlowConfig\Interfaces\ReadonlyConfigRepositoryInterface: '@CodeFoundation\FlowConfig\Repository\ReadonlyConfig'
    CodeFoundation\FlowConfig\Interfaces\ConfigRepositoryInterface: '@CodeFoundation\FlowConfig\Repository\DoctrineConfig'
    CodeFoundation\FlowConfig\Interfaces\EntityConfigRepositoryInterface: '@CodeFoundation\FlowConfig\Repository\DoctrineEntityConfig'
    CodeFoundation\FlowConfig\Interfaces\CompositeConfigRepositoryInterface:
      class: CodeFoundation\FlowConfig\Repository\CascadeConfig
      public: true
      arguments:
      - '@CodeFoundation\FlowConfig\Repository\ReadonlyConfig'
      - '@CodeFoundation\FlowConfig\Repository\DoctrineConfig'
      - '@CodeFoundation\FlowConfig\Repository\DoctrineEntityConfig'

    # Config aliases, cleanup needed.

    flowconfig.system:
      class: CodeFoundation\FlowConfig\Repository\DoctrineConfig
      public: true
    flowconfig.entity:
      class: CodeFoundation\FlowConfig\Repository\CodeFoundation\FlowConfig\Repository\CascadeConfig
      public: true
