services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  CodeFoundation\FlowConfig\Repository\ReadonlyConfig:
    arguments:
      $config: []

  CodeFoundation\FlowConfig\Repository\DoctrineConfig: ~
  CodeFoundation\FlowConfig\Repository\DoctrineEntityConfig: ~

  CodeFoundation\FlowConfig\Repository\CascadeConfig:
    class:
    arguments:
    - '@CodeFoundation\FlowConfig\Repository\ReadonlyConfig'
    - '@CodeFoundation\FlowConfig\Repository\DoctrineConfig'
    - '@CodeFoundation\FlowConfig\Repository\DoctrineEntityConfig'

  CodeFoundation\FlowConfig\Interfaces\ReadonlyConfigRepositoryInterface:
    alias: CodeFoundation\FlowConfig\Repository\ReadonlyConfig
    public: true
  CodeFoundation\FlowConfig\Interfaces\ConfigRepositoryInterface:
    alias: CodeFoundation\FlowConfig\Repository\DoctrineConfig
    public: true
  CodeFoundation\FlowConfig\Interfaces\EntityConfigRepositoryInterface:
    alias: CodeFoundation\FlowConfig\Repository\DoctrineEntityConfig
    public: true
  CodeFoundation\FlowConfig\Interfaces\CompositeConfigRepositoryInterface:
    alias: CodeFoundation\FlowConfig\Repository\CascadeConfig
    public: true

  flowconfig.ro:
    alias: CodeFoundation\FlowConfig\Repository\ReadonlyConfig
    public: true
  flowconfig.system:
    alias: CodeFoundation\FlowConfig\Repository\DoctrineConfig
    public: true
  flowconfig.entity:
    alias: CodeFoundation\FlowConfig\Repository\DoctrineEntityConfig
    public: true
  flowconfig.cascade:
    alias: CodeFoundation\FlowConfig\Repository\CascadeConfig
    public: true
